export const joinRequests = [
  {
    id: '1',
    name: 'Jake Readman',
    localAuthority: 'Jake',
    type: 'charity',
    email: 'Jakereadman@gmail.com',
    school: '',
    jobTitle: 'Job',
    phone: '+447595870150',
    charityName: 'Name',
    charityAddress:
      '30A Wilbury Road\n          \n          Hove\n          Eas sussex\n          BN3 3JP\n          ',
    aboutCharity: 'dfgvsd;fgjknsd;fglbksd',
    status: 'DENIED',
    requestTime: 1709907117044,
  },
  {
    id: '2',
    name: 'Ryan Smith',
    localAuthority: 'Hackney',
    type: 'school',
    email: 'team@donatetoeducate.org.uk',
    school: 'St John the Baptist Voluntary Aided Church of England Primary School - N1 6JG',
    jobTitle: 'sdv',
    phone: '07546547334',
    charityName: null,
    charityAddress: null,
    aboutCharity: null,
    status: 'NEW',
    requestTime: 1709819190636,
  },
];
