name: 'Backend'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  workflow_run:
    workflows: [Terraform] # Name of GitHub workflow to trigger in target repository
    types:
      - completed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-west-2'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install
        run: |
          npm install

      - name: Test
        run: npm test

      - name: Start LocalStack
        run: |
          pip install localstack awscli-local[ver1]
          docker pull localstack/localstack
          localstack start -d

          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
          echo "Startup complete"

      - name: Build
        run: npm run build

      - name: Move Zip files
        run: |
          mkdir archives
          mv .serverless/*.zip archives

      - name: Copy Zip files to S3
        run: aws s3 cp archives s3://d2e-lambda-s3-bucket/${GITHUB_REF##*/}/ --recursive

      - name: Copy GraphQL schema to S3
        run: aws s3 cp --content-type text/plain schema.graphql s3://d2e-lambda-s3-bucket/${GITHUB_REF##*/}/

      - name: Trigger Terraform
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/CapgeminiInventUK/donate-to-educate-terraform/actions/workflows/terraform.yml/dispatches \
          -d '{"ref":"main"}'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
