on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-west-2'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install
        run: |
          npm install
          python3 -m pip install --upgrade localstack

      - name: Build
        run: npm run build

      - name: Copy zip files to S3
        run: aws cp .serverless/*.zip
